### PR TITLE
Update for PuLP 2.4

### PR DESCRIPTION
**Pull request by venaturum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by venaturum** [comment]
@johanneskoester

This pull request looks to be the same as the v2.4 pull request by the cf regro autotick bot (from a month ago), with one exception - I am asking to be putting on the list of maintainers.

**Comment by venaturum** [comment]
@conda-forge/core 

Can I get a merge on this please?  The recipe is not being actively maintained...

**Comment by venaturum** [comment]
@johanneskoester @conda-forge/core

Bump

**Comment by chrisburr** [comment]
@venaturum Can you add yourself to the list of maintainers inside the `meta.yaml`? The one in the README gets regenerated every time the recipe is rerendered.

**Comment by venaturum** [comment]
@chrisburr done, thanks!

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
